set(CMAKE_C_FLAGS_INIT                "-Wall -std=c11")
set(CMAKE_C_FLAGS_DEBUG_INIT          "-g")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT     "-Os -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT        "-O3 -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")

set(CMAKE_CXX_FLAGS_INIT                "-Wall -std=c++20")
set(CMAKE_CXX_FLAGS_DEBUG_INIT          "-g")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "-Os -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT        "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")

if(USE_LLVM_TOOLS)
    set(CMAKE_AR      llvm-ar)
    #set(CMAKE_LINKER  llvm-ld)
    set(CMAKE_NM      llvm-nm)
    set(CMAKE_OBJDUMP llvm-objdump)
    set(CMAKE_RANLIB  llvm-ranlib)
endif()